inherit_from: .rubocop_todo.yml
Documentation:
    Enabled: false
AllCops:
  Excludes:
    - config.ru
    - Rakefile
    - Gemfile
    - config/unicorn.rb
    - db/**
    - test/**
    - '**/app/helpers/**/*'
    - '**/app/uploaders/**/*'
    - '**/test/**/*'
    - '**/db/**/*'
    - '**/config/**/*'
    - '**/bin/**'
    - '**/app/admin/**'
  Rails:
    Enabled: true
Metrics/LineLength:
  # This will disable the rule completely, regardless what other options you put
  Enabled: false
  # Change the default 80 chars limit value
  Max: 120
